---
title: "Fire Count"
output: 
    html_document:
      code_folding: hide
---

```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
library(plotly)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r load in data, include = FALSE}
fire_df = read_csv("./data/forestfires.csv")
fire_df
```


```{r 1201 combine barcharts, echo = FALSE, warning = FALSE}
fire_mon = 
  fire_df %>%
  select(month, area) %>%
  filter(area > 0) %>%
  count(month) %>%
  add_row(month = 'Jan', n = 0) %>%
  add_row(month = 'Nov', n = 0) %>%
  mutate(month = stringi::stri_trans_totitle(month)) %>%
  mutate(month = factor(month, 
                        levels = c('Jan', 'Feb', 'Mar', 'Apr',
                                   'May', 'Jun', 'Jul', 'Aug',
                                   'Sep', 'Oct', 'Nov', 'Dec'),
                        ordered = TRUE))

month_df = 
  fire_df %>%
  select(month, area) %>%
  mutate(month = stringi::stri_trans_totitle(month)) %>%
  mutate(month = factor(month, 
                        levels = c('Jan', 'Feb', 'Mar', 'Apr',
                                   'May', 'Jun', 'Jul', 'Aug',
                                   'Sep', 'Oct', 'Nov', 'Dec'),
                        ordered = TRUE)) %>%
  count(month)
  

fire_m_df = merge(month_df, fire_mon, by = 'month')
fire_m_df %>%
  mutate(month = factor(month, 
                        levels = c('Jan', 'Feb', 'Mar', 'Apr',
                                   'May', 'Jun', 'Jul', 'Aug',
                                   'Sep', 'Oct', 'Nov', 'Dec'),
                        ordered = TRUE),
         sample_size = n.x,
         fire_count = n.y) %>% 
  select(month, sample_size, fire_count) %>% 
  knitr::kable()

fire_mon_p = plot_ly(fire_m_df)
fire_mon_p = 
  fire_mon_p %>% add_trace(x = ~month, y = ~n.x, type = 'bar', name = 'n (numbers of data)', marker = list(color = '#CFD8DC'), hoverinfo = "text", text = ~paste(month, ': n=', n.x))

fire_mon_p = 
  fire_mon_p %>% add_trace(x = ~month, y = ~n.y, type = 'bar', name = 'Fire Count(s)', marker = list(color = '#FF7043'), hoverinfo = "text", text = ~paste(month,': fire(s) = ', n.y))

fire_mon_p = 
  fire_mon_p %>% 
  layout(title = 'Fire Counts & Sample Size',
         yaxis = list(title = 'Count(s)'))
fire_mon_p

```

