---
title: "Investiagtion on Variables in fire days and no-fire days"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    source: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(shiny)
library(flexdashboard)
library(rsconnect)

```

```{r, include = FALSE}
# Load in data
fire_df = read_csv("./data/forestfires.csv")
# select and tidy data
fire_box = 
  fire_df %>% 
  select(FFMC, DMC, DC, ISI, temp, RH, wind, rain, area) %>% 
  mutate(fire = ifelse(area > 0, "fire", "no fire")) %>% 
  pivot_longer(FFMC:rain,
               names_to = "climate",
               values_to = "value") %>% 
  mutate(
    climate = replace(climate, climate == 'temp', 'Temperature'),
    climate = replace(climate, climate == 'RH', 'Relative Humidity'),
    climate = replace(climate, climate == 'wind', 'Wind Speed'),
    climate = replace(climate, climate == 'rain', 'Rain')
  )

```

Column {.sidebar}
-----------------------------------------------------------------------

```{r}
climate = fire_box %>% 
  pull(climate) %>% 
  unique()

selectInput(
  "climate",
  h3("Climate Variables"),
  choices = climate
)
```

Column {}
-----------------------------------------------------------------------

### Boxplot With Fire

```{r}
renderPlotly({
  fire_box %>% 
    filter(climate == input[["climate"]]) %>% 
    group_by(fire) %>% 
    plot_ly(
      y = ~value, x = ~fire, color = ~fire,
      type = "box", colors = "viridis")
})

```


Column {}
-----------------------------------------------------------------------
### Distribution

```{r}

distribution_plot = function(variable){
  
  plot_df = fire_box %>% 
    filter(
      climate == variable
    )
  
  fire_plot = 
    plot_df %>% 
    filter(fire == "fire")
  
  no_fire_plot = 
    plot_df %>% 
    filter(fire == "no fire")
  
  ggplot(fire_plot, aes(x = value)) +
    geom_density(color = "red", fill = "pink", alpha = 0.5) +
    geom_density(data = no_fire_plot, color = "blue", fill = "lightskyblue2", alpha = 0.5) +
    labs(title = "Density Plot: fire(red) & no fire(blue) days",
         x = variable)
  
}

renderPlot(distribution_plot(variable = input[["climate"]]))


```


### T-Test

```{r}

ttest = function(variable){
  test_df = fire_box %>% 
    filter(
      climate == variable
    )
  
  fire_test = 
    test_df %>% 
    filter(fire == "fire") %>% 
    select(value)
  
  no_fire_test = 
    test_df %>% 
    filter(fire == "no fire") %>% 
    select(value)

  results = t.test(fire_test$value, no_fire_test$value)
  
  results
}

renderPrint(ttest(variable = input[["climate"]]))


renderPrint(
  if (ttest(variable = input[["climate"]])$p.value < 0.05) {
    print("p-value < 0.05, we reject the null hypothesis, and conclude that the variable means in fire days and no fire days  have significant difference.")
  } else {
    print("p-value > 0.05, we fail to reject the null hypothesis, and conclude that the variable means in fire days and no fire days have no significant difference.")
  }
  
)

  
```



