---
title: "Linear Modeling"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)
library(broom)
library(modelr)
library(plotly)
library(ggplot2)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_color_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

### Linear Regression Model

formula = ...

```{r model, include = FALSE}
fire_linear = 
  read_csv("./data/forestfires.csv") %>% 
  select(FFMC, DMC, DC, ISI, temp, RH, wind, rain, area) %>% 
  filter(area > 0)

# linear model
fit = lm(area ~ FFMC + DMC + DC + ISI + temp + RH + wind + rain, data = fire_linear)

model = 
  fit %>% 
  tidy() %>% 
  select(-std.error, -statistic)
```

Here is the plot

```{r, echo = FALSE, warning = FALSE}
# plot for coefficients
coef_plot = 
  model %>% 
  filter(!term == "(Intercept)") %>% 
  mutate(
    text_label = str_c("Climate Variable: ", term, "\np-value: ", p.value)
  ) %>% 
  plot_ly(
    y = ~estimate, x = ~term, 
    text = ~text_label,
    type = "bar", color = "viridis"
  ) %>% 
  layout(
    title = "Coefficients for Each Climate Variable",
    xaxis = list(title = "Climate Variable"),
    yaxis = list(title = "Coefficient for Linear Model")
  )

coef_plot
```


### Diagnostics
```{r}
add_residuals(fire_linear, fit) %>%
  plot_ly(
    y = ~resid, type = "violin"
  ) %>% 
  layout(
    title = "Boxplot for Residuals",
    xaxis = list(title = "Climate Variable"),
    yaxis = list(title = "Residual", range = c(-200, 300))
  )


```

# Think about confounders... and discuss

### Cross Validation
Look at prediction accuracy
training data and testing data


```{r}
fire_id = 
  fire_linear %>% 
  mutate(
    id = 1:270
  )

train_df = sample_n(fire_id, size = 189)
test_df = anti_join(fire_id, train_df, by = "id")

fit_cv = lm(area ~ FFMC + DMC + DC + ISI + temp + RH + wind + rain, data = train_df)

rmse(fit_cv, test_df) # prediction accuracy


cv_df = 
  crossv_mc(fire_id, 100)

```








